# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-21 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0002_auto_20181021_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='email_address',
        ),
    ]
